name: Megaplex Theatres
safe: true
lsi: false
pygments: true

# baseurl: "/megaplex-theatres"
# url: "http://localhost:4000/megaplex-theatres"

# url: "http://designerdean.github.io/megaplex-theatres/"
# baseurl: "/"

baseurl: "/megaplex-theatres"

